version: "3"
services:
  pinger:
    image: github.com/hsmtkk/docker_fluentd/pinger
    depends_on:
      - fluentd
      - squid
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: docker.pinger
  squid:
    image: github.com/hsmtkk/docker_fluentd/squid
    depends_on:
      - fluentd
      - nginx
    volumes:
      - "./squid/var/logs:/usr/local/squid/var/logs"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: docker.squid
  squid_logger:
    image: fluent/fluent-bit:1.4
    depends_on:
      - squid
    command: /fluent-bit/bin/fluent-bit --config=/fluent-bit.conf
    volumes:
      - "./squid/var/logs:/usr/local/squid/var/logs:ro"
      - "./squid_logger/fluent-bit.conf:/fluent-bit.conf:ro"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: docker.squid_logger
  nginx:
    image: nginx:1.17.10
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: docker.nginx
  fluentd:
    image: fluent/fluent-bit:1.4
    command: /fluent-bit/bin/fluent-bit --config=/fluent-bit.conf
    volumes:
      - "./fluentd/fluent-bit.conf:/fluent-bit.conf:ro"
    ports:
      - "24224:24224"
